---
  title: "Salary Analysis 
author: "Alyssa"
date: "`r Sys.Date()`"
output: html_document:
  theme: united
highlight: tango
df_print: paged
pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Salary Data
```{r}
salaryData <- read.csv('/Users/daysg/Desktop/git-repo/Team-Anova-Project/Alyssa WIP/salary_data_states.csv')

```


```{r}
# R install package
install.packages('magrittr')
install.packages('ggplot2')


#import the package
library(magrittr)
library(dplyr)
#import data

```
```{r}
head(salaryData)
summary(salaryData)

avg_salary_by_subgroup <- salaryData %>% 
  group_by(JOB_TITLE_SUBGROUP) %>%
  summarize(AvgSalary = mean(PAID_WAGE_SUBMITTED))

avg_salary_by_subgroup
```


```{r}
avg_salary_by_employer <- salaryData %>%
  group_by(JOB_TITLE_SUBGROUP, EMPLOYER_NAME) %>%
  summarize(AvgSalary = mean(PAID_WAGE_SUBMITTED)) %>%
  filter(AvgSalary == max(AvgSalary, na.rm=TRUE)) %>%
  arrange(desc(AvgSalary))
avg_salary_by_employer

```

```{r}
med_salary_by_employer <- salaryData %>%
  group_by(JOB_TITLE_SUBGROUP, WORK_STATE, EMPLOYER_NAME) %>%
  summarize(MedSalary = median(PAID_WAGE_SUBMITTED)) %>%
  filter(MedSalary == max(MedSalary, na.rm=TRUE)) %>%
  arrange(desc(MedSalary))
med_salary_by_employer
```





```{r}
avg_salary_by_workcity <- salaryData %>% 
  group_by(WORK_CITY) %>%
  summarize(AvgCITYSalary = mean(PAID_WAGE_SUBMITTED)) %>%
  arrange(desc(AvgCITYSalary))


avg_salary_by_workcity
```
```{r}
avg_salary_by_location <- salaryData %>% 
  group_by(EMPLOYER_NAME, WORK_CITY, WORK_STATE_ABBREVIATION, JOB_TITLE_SUBGROUP) %>%
  summarize(AvgSalary = mean(PAID_WAGE_SUBMITTED)) %>%
  arrange(desc(AvgSalary))
avg_salary_by_location
```



```{r} 
median_salary_by_location <- salaryData %>% 
  group_by(WORK_STATE) %>%
  summarize(MedPlaceSalary = median(PAID_WAGE_PER_YEAR)) %>%
  arrange(desc(MedPlaceSalary))
median_salary_by_location

```
```{r}
salary_by_location <- salaryData %>% 
  group_by(WORK_STATE, EMPLOYER_NAME) %>%
  summarize(AvgSalary = mean(PAID_WAGE_PER_YEAR)) %>%
  filter(AvgSalary == max(AvgSalary, na.rm=TRUE)) %>%
  arrange(desc(AvgSalary))
salary_by_location
```
```{r}
location_a <- salary_CA_subset %>%
  group_by(JOB_TITLE_SUBGROUP) %>%
  summarize(CA_MedianSalary = median(PAID_WAGE_PER_YEAR)) %>%
  arrange(desc(CA_MedianSalary))
location_a
```
```{r}
salary_CA_subset = subset(salaryData, WORK_STATE == "California")
```

```{r}
salary_MA_subset = subset(salaryData, WORK_STATE == "Massachusetts")
location_MA <- salary_MA_subset %>%
  group_by(JOB_TITLE_SUBGROUP) %>%
  summarize(MA_MedianSalary = median(PAID_WAGE_PER_YEAR)) %>%
  arrange(desc(MA_MedianSalary))
location_MA
```


